### ISSUE TITLE
Initial implementation

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-authz-service#1]
# Description

The OpenSpending Datastore is an S3-backed flat file storage. 

This datastore will hold fiscal data packages. 

Users need to upload fiscal data packages. 

"Users" can be actual users of the OpenSpending system, or, other services that programmatically access the datastore.

We are **not** concerned with implementing *authentication* right now. We'll have a set of "known keys" setup via an env var, and pass them out to initial parties/apps until we integrate with authentication.

We **are** concerned with authorisation to write to the datastore. For S3, that means:

* getting from the user a bunch of info on files the user wants to add to the datastore
* for each file, using that info, generate a temporary access key - this key is used to allow the upload, and verify that the thing being uploaded is the thing that was authorised for upload.
* give the user these access keys

We already have a proof of concept implementation of this in the [OpenSpending Datastore CLI](https://github.com/openspending/os-datastore-cli) (A CLI that pushes data to the datastore is a great example of a user for this authz service). There, the flow goes something like this:

**pre**: User does all sorts of data modelling and data package validation stuff.

*  User executes an `upload` command which ([ref.](https://github.com/openspending/os-datastore-cli/blob/master/oscli/upload/upload.py#L61)):
  * Collects al the files of the data package
  * Collects metrics on all the files like name, checksum, length ([ref.](https://github.com/openspending/os-datastore-cli/blob/master/oscli/upload/upload.py#L124))
  * Sends this payload of file metadata to the datastore authz service (which is a mock of how such a service might look) ([ref.](https://github.com/openspending/os-datastore-cli/blob/master/oscli/upload/upload.py#L65))

* The Datastore authz service takes a payload from a "known user" ([ref.](https://github.com/openspending/os-datastore-cli/blob/master/oscli/_mock/storage.py#L15))
  * For each file, generates an s3 access token ([ref.](https://github.com/openspending/os-datastore-cli/blob/master/oscli/_mock/storage.py#L50))
  * Returns the updated "file payload", with the new access tokens, to the user ([ref.](https://github.com/openspending/os-datastore-cli/blob/master/oscli/_mock/storage.py#L61) and [ref.](https://github.com/openspending/os-datastore-cli/blob/master/oscli/_mock/storage.py#L64))

* With the new tokens that allow the payload files to be uploaded to the Datastore, the user uploads :) ([ref.](https://github.com/openspending/os-datastore-cli/blob/master/oscli/upload/upload.py#L72))

# Tasks

* [x] Bootstrap a simple flask app, `os_authz`
  * Add a blueprint for `datastore`
    * We will have other authz needs for OpenSpending that will also be implemented via this authz service - now, we are just concerned with datastore access
  * The app supports CORS
* [x] Basically, the app exposes functionality similar to the [class here that mocks such a service](https://github.com/openspending/os-datastore-cli/blob/master/oscli/_mock/storage.py#L15)
  * [x] User gives an `api_key` for any request. Should be through auth headers i guess, but don't over-engineer as we will swap this out relatively soon
  * [x] User request json is a payload of `{"metadata": {}, "filedata": []}`, roughly corresponding with the `descriptor` and `payload` args of [this](https://github.com/openspending/os-datastore-cli/blob/master/oscli/_mock/storage.py#L36)
  * [x] response object is `{"filedata": []}`, roughly [corresponding with this](https://github.com/openspending/os-datastore-cli/blob/master/oscli/_mock/storage.py#L66)
* [x] Config: `API_KEY_WHITELIST` is just a comma-separated list env var, that should be read into a `list` and is the lookup table for user api keys
* [x] Config: All AWS creds available via env vars > config
* [x] Deploy to Heroku
* [x] Unit tests
* [x] Functional tests
